/**
 * Turn discovered components into (a) the remote's `src/capability.ts` and (b) the
 * per-component `kind:'component'` catalog bodies. The capability module is the
 * exact shape the host loads via `loadRemoteModule('./Capability')` (mirrors
 * `matter-management-mfe/src/app/capability.ts`).
 */
import type { DiscoveredComponent, PropType } from './introspect.js';

export interface RemoteMeta {
  readonly remoteName: string;
  readonly version: string;
  /** The uploaded library's package name — components are imported from it. */
  readonly packageName: string;
}

/** A Zod field expression for one classified input type. */
function zodField(t: PropType): string {
  switch (t.kind) {
    case 'string': return 'z.string()';
    case 'number': return 'z.number()';
    case 'boolean': return 'z.boolean()';
    case 'enum': return t.enum && t.enum.length ? `z.enum([${t.enum.map(q).join(', ')}])` : 'z.string()';
    case 'array': return 'z.array(z.unknown())';
    case 'object': return 'z.record(z.string(), z.unknown())';
    default: return 'z.unknown()';
  }
}

/** A `propsSchema` expression for a component: typed inputs (all optional) + passthrough. */
export function propsSchemaExpr(c: DiscoveredComponent): string {
  const entries = Object.entries(c.inputTypes);
  if (!entries.length) return 'z.object({}).passthrough()';
  const fields = entries.map(([name, t]) => `${q(name)}: ${zodField(t)}.optional()`).join(', ');
  return `z.object({ ${fields} }).passthrough()`;
}

/** Generate the remote's `src/capability.ts` — typed props schema per component. */
export function generateCapabilityTs(meta: RemoteMeta, components: readonly DiscoveredComponent[]): string {
  // Real libraries (PrimeNG, Kendo, …) export each component from its own secondary
  // entry point (`primeng/button`), so group class imports by their resolved path.
  const byPath = new Map<string, Set<string>>();
  for (const c of components) {
    const path = c.importPath || meta.packageName;
    (byPath.get(path) ?? byPath.set(path, new Set()).get(path)!).add(c.className);
  }
  const imports = [...byPath.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([path, classes]) => `import { ${[...classes].sort().join(', ')} } from ${q(path)};`)
    .join('\n');
  const widgets = components.map((c) =>
    `    agenticWidget({ name: ${q(c.widgetName)}, component: ${c.className}, propsSchema: ${propsSchemaExpr(c)} }),`).join('\n');
  return `// AUTO-GENERATED by component-ingest-service. Do not edit.
import { defineCapabilityModule, agenticWidget } from '@infra-tools/agentic-ui';
import { z } from 'zod';
${imports}

export const capability = defineCapabilityModule({
  remoteName: ${q(meta.remoteName)},
  version: ${q(meta.version)},
  components: [
${widgets}
  ],
});
`;
}

/** The `kind:'component'` catalog body for one discovered component (Studio discoverability). */
export function componentCatalogBody(
  meta: RemoteMeta, remoteEntryUrl: string, c: DiscoveredComponent,
): { kind: 'component'; name: string; lifecycle: 'published'; body: Record<string, unknown> } {
  return {
    kind: 'component',
    name: c.widgetName,
    lifecycle: 'published',
    body: {
      description: `${c.className} from ${meta.packageName}`,
      library: meta.packageName,
      version: meta.version,
      remoteName: meta.remoteName,
      exposedModule: './Capability',
      manifestUrl: remoteEntryUrl,
      selector: c.selector,
      inputs: c.inputs,
      inputTypes: c.inputTypes,
    },
  };
}

function q(s: string): string { return `'${s.replace(/'/g, "\\'")}'`; }
