/**
 * Turn discovered components into (a) the remote's `src/capability.ts` and (b) the
 * per-component `kind:'component'` catalog bodies. The capability module is the
 * exact shape the host loads via `loadRemoteModule('./Capability')` (mirrors
 * `matter-management-mfe/src/app/capability.ts`).
 */
import type { DiscoveredComponent } from './introspect.js';

export interface RemoteMeta {
  readonly remoteName: string;
  readonly version: string;
  /** The uploaded library's package name — components are imported from it. */
  readonly packageName: string;
}

/** Generate the remote's `src/capability.ts` (passthrough props schema — MVP). */
export function generateCapabilityTs(meta: RemoteMeta, components: readonly DiscoveredComponent[]): string {
  const classes = [...new Set(components.map((c) => c.className))].join(', ');
  const widgets = components.map((c) =>
    `    agenticWidget({ name: ${q(c.widgetName)}, component: ${c.className}, propsSchema: anyProps }),`).join('\n');
  return `// AUTO-GENERATED by component-ingest-service. Do not edit.
import { defineCapabilityModule, agenticWidget } from '@infra-tools/agentic-ui';
import { z } from 'zod';
import { ${classes} } from ${q(meta.packageName)};

/** MVP: props are forwarded as-is; the host validates against this permissive schema. */
const anyProps = z.object({}).passthrough();

export const capability = defineCapabilityModule({
  remoteName: ${q(meta.remoteName)},
  version: ${q(meta.version)},
  components: [
${widgets}
  ],
});
`;
}

/** The `kind:'component'` catalog body for one discovered component (Studio discoverability). */
export function componentCatalogBody(
  meta: RemoteMeta, remoteEntryUrl: string, c: DiscoveredComponent,
): { kind: 'component'; name: string; lifecycle: 'published'; body: Record<string, unknown> } {
  return {
    kind: 'component',
    name: c.widgetName,
    lifecycle: 'published',
    body: {
      description: `${c.className} from ${meta.packageName}`,
      library: meta.packageName,
      version: meta.version,
      remoteName: meta.remoteName,
      exposedModule: './Capability',
      manifestUrl: remoteEntryUrl,
      selector: c.selector,
      inputs: c.inputs,
    },
  };
}

function q(s: string): string { return `'${s.replace(/'/g, "\\'")}'`; }
